### ISSUE TITLE
Possible Auto Size checker?

### ISSUE THREAD

**Issue by MrTommo999** [PokemonAutomation/About#5]
is there any plan for a size checker for boxes? i have over 200 shinies i have caught/breeded for months but forgot to check them as i got them. will there ever be a auto system that allows the bot to check each mon i caught/breeded size so i don't have to go though the 30+boxes for my whole collection?

**Comment by Mysticial** [comment]
Refile this in the CC repo since this is just the About page.

https://github.com/PokemonAutomation/ComputerControl/issues
